oblasts <- list()
oblasts <- c(oblasts, list(list(shapeISO = "UA-07", name = "Волинська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-56", name = "Рівненська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-18", name = "Житомирська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-32", name = "Київська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-74", name = "Чернігівська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-59", name = "Сумська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-63", name = "Харківська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-09", name = "Luhanks oblast")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-14", name = "Донецька_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-23", name = "Запорізька_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-46", name = "Львівська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-26", name = "ІваноФранківська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-21", name = "Закарпатська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-61", name = "Тернопільська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-77", name = "Чернівецька_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-51", name = "Одеська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-48", name = "Миколаївська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-43", name = "Autonomous Republic of Crimea")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-05", name = "Вінницька_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-68", name = "Хмельницька_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-71", name = "Черкаська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-53", name = "Полтавська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-12", name = "Дніпропетровська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-35", name = "Кіровоградська_область")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-30", name = "м_Київ")))
oblasts <- c(oblasts, list(list(shapeISO = "UA-40", name = "Sevastopol")))
